# Generated by Django 5.1.1 on 2024-12-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(max_length=50, unique=True)),
                ('visitor_name', models.CharField(max_length=100)),
                ('visitor_email', models.EmailField(max_length=254)),
                ('category', models.CharField(max_length=50)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('reason', models.TextField()),
                ('designated_attendee', models.CharField(max_length=100)),
                ('attendee_availability', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
