# Generated by Django 5.1.1 on 2024-12-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_visitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='attendee_availability',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='document',
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitor_id',
            field=models.CharField(max_length=50),
        ),
    ]
