# Generated by Django 5.1.1 on 2024-12-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_visitor_attendee_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='visitor_documents/'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitor_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
