# Generated by Django 5.1.3 on 2024-12-05 10:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_profile_profile_pic_profile_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='work_email',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='full_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='emp_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='profile_pictures/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='reporting_to',
            field=models.CharField(max_length=255),
        ),
    ]
