# Generated by Django 5.1.3 on 2024-12-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_visitor_attendee_availability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='attendee_availability',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='rescheduled_date',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='rescheduled_time',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='status',
        ),
        migrations.AlterField(
            model_name='visitor',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='designated_attendee',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='visitor_documents/'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitor_id',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitor_name',
            field=models.CharField(max_length=100),
        ),
    ]
