# Generated by Django 5.1.3 on 2024-12-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_visitorschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
