# Generated by Django 5.1.3 on 2024-12-09 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_visitor_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RescheduledMeet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rescheduled_date', models.DateField()),
                ('rescheduled_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.visitor')),
            ],
        ),
    ]
