# Generated by Django 5.1.3 on 2024-12-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rescheduledmeet'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorschedule',
            name='verification_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
