# Generated by Django 5.1.3 on 2024-12-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_visitorschedule_feedback_visitorschedule_in_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorschedule',
            name='in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitorschedule',
            name='out_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
